//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public string Paciente { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Lugar { get; set; }
        public string Observaciones { get; set; }
        public string Status { get; set; }
        public override string ToString()
        {
            String str = Fecha.ToString("dd/MMM/yyyy hh:mm");
            return str;
        }
    }
}
