//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string SexoGenero { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public string Email { get; set; }
        public string Detalles { get; set; }
    }
}
